before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends latexmk
  texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra
  texlive-latex-recommended texlive-pictures texlive-science
script:
- mkdir _build
- latexmk -pdf -outdir=_build AllegThesis.tex
deploy:
  provider: releases
  api_key:
    secure: X+NFspIV0wSbcdZmB/pd1YOjBGbpRFiNO86kgJjp76NP0torcu/Q9b8Urgf6ntE5W/RnEZondlpqv1iP3dp5t4+stOkHJ7sAdNLdmz5rdaHY9NxCbbxHtvQ0x+ab16kt94OS+3Tt/+arsWFZ69+Ygm26hO7lPzix2jw0y8d3EUm9nV9nuBe1M8vF5ijI/keqJpyxVG11xGzKn0bVIDgInPzxY9tZAa55hTrAbur0nikKJlkvANlwDK2wXb9HTwqSUzZiGwfEpoN83BCYXMHGKrnJzZ256TjUI9OJ5w4M1VkXBlT0obxz/RnXnMpi/DQh0LuUseB5mOlLgOF+dCTFn95BoJq5fSYvn7OHfme/aU9EZCMCUijIYaKVEViDBbHmD14nCMv9ghobe/+kWb7Fi3GBr7k4IgvZIkLeFWhDSayeIlc7IAODGAoE/+s24zEK1m0X5vhehRfzNC1Hx5SRXhT6J/ftxfrkIiAdyL07Y2ehWy6tEw6Ohx3Kr3Be++vcjdbEDDRPjcTo02y3n+3mkeaPGdsjNJs4HxbyfZskx5uuRGkfgpgk37nyrCb/bm9KGG/jEje+VKAdAgpmXrJ8UY0UBVNmYydBEyo72OslzOtu/Z4bcsPZtf+HF1lcouqqsApAvSKdLKMAuX4v/roHwdpLAopoipCOYfLSBpJlOaM=
  file: _build/AllegThesis.pdf
  skip_cleanup: true
  on:
    tags: true
